### ISSUE TITLE
Landscape Mobile UI is missing darkmode icon and menu does not scroll (when scrolling content)

### ISSUE THREAD

**Issue by youzi** [atelier-saulx/aviato#110]
![image](https://user-images.githubusercontent.com/5662898/148747595-836865eb-49dd-488f-8aa6-70c8a2d554dd.png)

- [ ] Missing darkmode icon
- [ ] After scrolling content on iOS, try scrolling the menu => this will scroll the content instead of menu

**Comment by mortenbroesby** [comment]
Fixed in previous release
